image: docker

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
  - test
  - build

test:
  stage: test
  services:
    - docker:dind
    - mongo
  script:
    - export URL_MONGODB="mongodb://mongo:27017/"
    - apk update
    - apk add gcc build-base musl-dev zlib zlib-dev libpng-dev libffi-dev openssl-dev libgcc linux-headers python3 python3-dev
    - python3 -m pip install --upgrade pip
    - pip install --no-cache-dir -r requirements.txt
    - pytest --verbose --showlocals --tb=auto --cov=db --cov=routers --cov=utils

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - develop

