image: docker

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  RSA_PUBLIC_KEY: $TEST_RSA_PUBLIC_KEY
  RSA_PRIVATE_KEY: $TEST_RSA_PRIVATE_KEY

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

stages:
  - test
  - build

test:
  stage: test
  services:
    - docker:dind
    - mongo:4.2.1
  script:
    - export MONGO_TEST_HOST="mongo"
    - export MONGO_TEST_PORT=27017
    - apk update
    - apk add gcc build-base musl-dev zlib zlib-dev libpng-dev libffi-dev openssl-dev libgcc linux-headers python3 python3-dev
    - python3 -m pip install --upgrade pip
    - pip install --no-cache-dir -r requirements.txt
    - pytest --verbose --showlocals --tb=native --cov=db --cov=routers --cov=utils

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - develop

